
    .align 3
    .section .data
    .global _num_app
_num_app:
    .quad 2
    .quad app_0_start
    .quad app_1_start
    .quad app_1_end

    .section .data
    .global app_0_start
    .global app_0_end
    .align 3
app_0_start:
    .incbin "../six_os_user_lib/target/riscv64gc-unknown-none-elf/release/hello_world0"
app_0_end:

    .section .data
    .global app_1_start
    .global app_1_end
    .align 3
app_1_start:
    .incbin "../six_os_user_lib/target/riscv64gc-unknown-none-elf/release/hello_world1"
app_1_end:
